//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudeApplicationDemo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UspRoughEntities1 : DbContext
    {
        public UspRoughEntities1()
            : base("name=UspRoughEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Emp> Tbl_Emp { get; set; }
    
        public virtual int Usp_Emp(string employeeName, string empId, string designation, Nullable<System.DateTime> dateOfBirth, Nullable<System.DateTime> dateOfRetirement, string contactNumber, string address, string fileUpload, string photoUpload)
        {
            var employeeNameParameter = employeeName != null ?
                new ObjectParameter("EmployeeName", employeeName) :
                new ObjectParameter("EmployeeName", typeof(string));
    
            var empIdParameter = empId != null ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(string));
    
            var designationParameter = designation != null ?
                new ObjectParameter("Designation", designation) :
                new ObjectParameter("Designation", typeof(string));
    
            var dateOfBirthParameter = dateOfBirth.HasValue ?
                new ObjectParameter("DateOfBirth", dateOfBirth) :
                new ObjectParameter("DateOfBirth", typeof(System.DateTime));
    
            var dateOfRetirementParameter = dateOfRetirement.HasValue ?
                new ObjectParameter("DateOfRetirement", dateOfRetirement) :
                new ObjectParameter("DateOfRetirement", typeof(System.DateTime));
    
            var contactNumberParameter = contactNumber != null ?
                new ObjectParameter("ContactNumber", contactNumber) :
                new ObjectParameter("ContactNumber", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var fileUploadParameter = fileUpload != null ?
                new ObjectParameter("FileUpload", fileUpload) :
                new ObjectParameter("FileUpload", typeof(string));
    
            var photoUploadParameter = photoUpload != null ?
                new ObjectParameter("PhotoUpload", photoUpload) :
                new ObjectParameter("PhotoUpload", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usp_Emp", employeeNameParameter, empIdParameter, designationParameter, dateOfBirthParameter, dateOfRetirementParameter, contactNumberParameter, addressParameter, fileUploadParameter, photoUploadParameter);
        }
    
        public virtual ObjectResult<Usp_EmpList_Result> Usp_EmpList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_EmpList_Result>("Usp_EmpList");
        }
    }
}
