//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;

namespace CrudeApplicationDemo
{
    internal class Tbl_EmpMetaData
    {
        public string EmpId { get; set; }
        [Required]
        public string EmployeeName { get; set; }
        [Required(ErrorMessage = "Enter Designation")]
        public string Designation { get; set; }

        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfRetirement { get; set; }
        [Required]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid phone number")]
        public string ContactNumber { get; set; }
        public string Address { get; set; }

        [RegularExpression(@"^.*\.(pdf|PDF)$", ErrorMessage = "File is not valid")]
        public string FileUpload { get; set; }
        [RegularExpression(@"^.*\.(jpg|JPG|jpeg|JPEG|png|PNG)$", ErrorMessage = "Photo is not valid")]
        public string PhotoUpload { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}