//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudeApplicationDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Emp
    {
        public int Id { get; set; }
        public string EmpId { get; set; }
        public string EmployeeName { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfRetirement { get; set; }
        public string ContactNumber { get; set; }
        public string Address { get; set; }
        public string FileUpload { get; set; }
        public string PhotoUpload { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
